<?php

namespace GFS\statistiquesBundle\Repository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEtudiantForStat() {
        $sql = 'SELECT e.id as idEtudiant, e.sexe, e.nationalite, n.nom as niveau,e.statut,
                    d.nom as nomDepartement, f.nom  as nomFormation, nE.resultat, nE.anneeAcademique 
                FROM
                    GFSstatistiquesBundle:Etudiant e,
                    GFSstatistiquesBundle:Niveau n,
                    GFSstatistiquesBundle:NiveauEtudiant nE,
                    GFSstatistiquesBundle:Formation f,
                    GFSstatistiquesBundle:Departement d,
                    GFSstatistiquesBundle:OptionDep o 
                where o.departement=d 
                    and f.optionDep = o 
                    and e.formation = f 
                    and nE.etudiant = e
                    and nE.niveau = n';
        return $this->getEntityManager()->createQuery($sql)->getResult();
    }
       
}
